### ISSUE TITLE
Implement FantasyLand ChainRec

### ISSUE THREAD

**Issue by safareli** [folktale/data.either#11]
As of [fantasyland/fantasy-land#152](https://github.com/fantasyland/fantasy-land/pull/152) implement [ChainRec](https://github.com/fantasyland/fantasy-land#chainrec) specification.

[MonadRec instance for either](https://github.com/purescript/purescript-tailrec/blob/master/src/Control/Monad/Rec/Class.purs#L89-L95) in purescript might be usefull

I would create PR when have time.

**Comment by robotlolita** [comment]
Ah, that looks nice. Can you open an issue on https://github.com/origamitower/folktale/issues instead?

**Comment by safareli** [comment]
should i do same for data.task?
