### ISSUE TITLE
Add Either.fromMaybe

### ISSUE THREAD

**Issue by floriansimon1** [folktale/data.either#16]
It would be interesting to be able to convert a Maybe to an Either, would it not? Or is there another way to do that?

**Comment by robotlolita** [comment]
It's available in the new version of the library as `Result.fromMaybe()` and `aMaybe.toResult()`.

The repo for the new version is here: https://github.com/origamitower/folktale
Documentation and migration guides here: http://folktale.origamitower.com/docs/v2.0.0/
