### ISSUE TITLE
documentation site is down

### ISSUE THREAD

**Issue by jethrolarson** [folktale/data.either#18]
http://docs.folktalejs.org/en/latest/api/data/either/Either.html

**Comment by robotlolita** [comment]
Ah, yeah, the new website is here: http://folktale.origamitower.com/

The documentation for the older version is now here: http://folktalegithubio.readthedocs.io/en/latest/api/data/either/Either.html

I have to update the links on the readmes, didn't realise it was still pointing to the old domain.
