### ISSUE TITLE
Idea: Add utility function to wrap exception throwing functions

### ISSUE THREAD

**Issue by AriaMinaei** [folktale/data.either#6]
_tl/dr: Add `Either.wrap()` to make a function return `Left`/`Write` instead of throwing._

I have a utility function like this:
```livescript
wrap = (fn) -> ->
  try
    val = fn ...arguments
    Either.Right val
  catch e
    Either.Left e
```

Which is used like this:
```livescript
parse-json = wrap JSON.parse
```

This way, `parse-json()` returns a `Left(Error)` if `JSON.parse()` throws.

The inconvenience here is that this is pretty much the only utility function I need to work with `data.either` (apart from the ones in `control.async`), so it doesn't make much sense to either put it in a separate lib, or copy/paste it in every project.

So, would it make sense to include `wrap()` as a static method of `Either`?

**Comment by robotlolita** [comment]
It's a useful method, yes. I don't see any problem in placing it inside `data.either` here. There are a few other utility functions, like `Either.fromValidation` which are also included, I feel this is a similar "conversion" utility.

I'd probably call it `Either.try`, `Either.attempt` or `Either.bracket` though.

**Comment by AriaMinaei** [comment]
Both `try` and `attempt` sound natural to my ears. Does `bracket` have some special meaning elsewhere?
