### ISSUE TITLE
unbound use of Either.of fails due to `this`

### ISSUE THREAD

**Issue by ericgj** [folktale/data.either#7]
Steps to reproduce:
```
var x = Either.of
x(1);  // TypeError: undefined is not a function
```
It seems it could be fixed by removing `this` (no?):
```js
Either.of = function(a) {
  return Right(a)
}
```

**Comment by robotlolita** [comment]
Sure, but that makes it harder to extend it. In particular, I don't see much of a problem with having to bind functions in JS.

**Comment by ericgj** [comment]
Hadn't considered that. It tripped me up using ramda `commute` . But no big deal to bind it in such cases. Thanks for your excellent libraries btw.
