### ISSUE TITLE
Left#ap should return itself, not other ?

### ISSUE THREAD

**Issue by ericgj** [folktale/data.either#8]
I would expect `Left('failure').ap( Right('ok') )` to return `Left('failure')`  

In which case it seems https://github.com/folktale/data.either/blob/master/lib/either.js#L180-182  should be
```js
Left.prototype.ap = function(b) {
  return this;  
}
```

There is a relevant discussion in ramda-fantasy [here](https://github.com/ramda/ramda-fantasy/issues/75).

**Comment by robotlolita** [comment]
Ah, yes, Left#ap should be returning `this`.
